# Generated by Django 2.2.1 on 2020-01-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logtailer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logfile',
            options={'verbose_name': 'Log file', 'verbose_name_plural': 'Log files'},
        ),
        migrations.AlterModelOptions(
            name='logsclipboard',
            options={'verbose_name': 'logs clipboard', 'verbose_name_plural': 'logs clipboard'},
        ),
        migrations.AlterField(
            model_name='logsclipboard',
            name='log_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logtailer.LogFile', verbose_name='log file'),
        ),
    ]
